packages:
  - 'packages/*'

catalog:
  "@prisma/adapter-pg": "^7.8.0"
  "@octokit/rest": "^22.0.1"
  "@types/node": "^24.12.2"
  "discord.js": "^14.26.4"
  "dotenv": "^17.4.2"
  "tsx": "^4.21.0"
  "typescript": "^6.0.3"
  "vitest": "^4.1.5"
  "zod": "^4.4.3"

syncInjectedDepsAfterScripts:
- build
injectWorkspacePackages: true
